apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-depl
  namespace: course-tracking

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express-container
          image: mongo-express
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: courses-tracking-secret
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: courses-tracking-secret
            - name: ME_CONFIG_MONGODB_SERVER
              value: courses-tracking-db-ip
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-ip
  namespace: courses-tracking
spec:
  type: ClusterIP
  selector:
    app: mongo-express
  ports:
    - name: mongo-express
      port: 8081
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-nodeport
  namespace: courses-tracking
spec:
  type: NodePort
  selector:
    app: mongo-express
  ports:
    - name: mongo-express
      port: 8081
      protocol: TCP
    
                
    
  