services:
  service:
    image: egonzalezatos/upgrade.trainee-tracking
    ports:
      - 5004:80
    environment:
      MONGO_USERNAME: admin
      MONGO_PASSWORD: admin
    depends_on: 
      - trainee-tracking-db
        
  trainee-tracking-cache:
    container_name: trainee-tracking-cache
    image: bitnami/redis:latest
    ports:
      - 6380:6379
    environment:
      REDIS_PASSWORD: admin

  course-service:
    image: egonzalezatos/courses
    ports:
      - 5003:5001
      - 667:667
  
  trainee-tracking-db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo-pv:/data/db
        
  trainee-tracking-db-management:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      
  profile-manage-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: profile-manage-db
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Admin123
    volumes:
      - mssql-pv:/var/opt/mssql
      
  profile-manage-service:
    image: egonzalezatos/upgrade.trainee-admin
    container_name: profile-manage-service
    ports:
      - 5005:80
    depends_on: 
      - profile-manage-db


volumes:
  mongo-pv:
  mssql-pv: