apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: courses-tracking-db-pvc
  namespace: courses-tracking
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi