apiVersion: apps/v1
kind: Deployment

metadata:
  name: courses-traking-redis
  namespace: courses-tracking
  
spec:
  selector:
    matchLabels:
      app: courses-tracking-redis
  template:
    metadata:
      labels:
        app: courses-tracking-redis
    spec:
      containers:
        - name: redis
          image: bitnami/redis:latest
          ports:
            - containerPort: 6379
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: courses-tracking-secret
              
---
#Cluster IP
apiVersion: v1
kind: Service
metadata:
  name: courses-tracking-redis-ip
  namespace: courses-tracking
spec:
  type: ClusterIP
  selector:
    app: courses-tracking-redis
  ports:
    - name: courses-tracking-redis
      port: 6379
      protocol: TCP

---
#Node Port
apiVersion: v1
kind: Service
metadata:
  name: courses-tracking-redis-nodeport
  namespace: courses-tracking
spec:
  type: NodePort
  selector:
    app: courses-tracking-redis
  ports:
    - name: courses-tracking-redis
      port: 6379
      nodePort: 30379

    